name: palynomoph_detection  # Replace with your preferred environment name
channels:
  - conda-forge
  - defaults
dependencies:
  # Conda packages
  - openjdk
  - pillow=10.1.0
  - openslide
  - numpy=1.25.2
  - pandas=2.2.3
  - python-dateutil=2.9.0.post0
  - pytz=2025.1
  - tzdata

  # Pip dependencies
  - pip
  - pip:
      - boto3==1.37.0
      - botocore==1.37.0
      - chardet==4.0.0
      - dbus-python==1.2.18
      - decorator==4.4.2
      - distro==1.5.0
      - file-magic==0.4.0
      - future==1.0.0
      - gpg==1.15.1
      - idna==2.10
      - iniparse==0.4
      - iotop==0.6
      - jmespath==1.0.1
      - libcomps==0.1.18
      - nftables==0.1
      - pcp==5.0
      - PyGObject==3.40.1
      - pyinotify==0.9.6
      - PySocks==1.7.1
      - python-bioformats==4.0.7
      - python-javabridge==4.0.3
      - PyYAML==5.4.1
      - requests==2.25.1
      - rpm==4.16.1.3
      - s3transfer==0.11.2
      - selinux==3.6
      - sepolicy==3.6
      - setools==4.4.4
      - six==1.17.0
      - subscription-manager==1.29.40
      - systemd-python==234
      - urllib3==1.26.5
      - openslide-python